const quotes = [
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
    "Accept the things to which fate binds you, and love the people with whom fate brings you together. - Marcus Aurelius",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "When you arise in the morning, think of what a precious privilege it is to be alive. - Marcus Aurelius",
    "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. - Marcus Aurelius",
    "What stands in the way becomes the way. - Marcus Aurelius",
    "Our life is what our thoughts make it. - Marcus Aurelius",
    "He who fears death will never do anything worthy of a man who is alive. - Seneca",
    "Life is very short and anxious for those who forget the past, neglect the present, and fear the future. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "We suffer more often in imagination than in reality. - Seneca",
    "As long as you live, keep learning how to live. - Seneca",
    "Associate with people who are likely to improve you. - Seneca",
    "If a man knows not to which port he sails, no wind is favorable. - Seneca",
    "The greatest power we have is the power of choice. - Seneca",
    "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
    "If you really want to escape the things that harass you, what you're needing is not to be in a different place but to be a different person. - Seneca",
    "First say to yourself what you would be; then do what you have to do. - Epictetus",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "The key is to keep company only with people who uplift you. - Epictetus",
    "Don't explain your philosophy. Embody it. - Epictetus",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. - Epictetus",
    "When we are no longer able to change a situation, we are challenged to change ourselves. - Marcus Aurelius",
    "The impediment to action advances action. What stands in the way becomes the way. - Marcus Aurelius",
    "To live a good life: We have the potential for it. If we learn to be indifferent to what makes no difference. - Marcus Aurelius",
    "Be tolerant with others and strict with yourself. - Marcus Aurelius",
    "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are. - Marcus Aurelius",
    "It is not death that a man should fear, but rather he should fear never beginning to live. - Marcus Aurelius",
    "Difficulties strengthen the mind, as labor does the body. - Seneca",
    "If a man knows not to which port he sails, no wind is favorable. - Seneca",
    "They lose the day in expectation of the night, and the night in fear of the dawn. - Seneca",
    "Begin at once to live, and count each separate day as a separate life. - Seneca",
    "It is the power of the mind to be unconquerable. - Seneca",
    "Sometimes even to live is an act of courage. - Seneca",
    "Man is affected not by events but by the view he takes of them. - Epictetus",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. - Epictetus",
    "Any person capable of angering you becomes your master. - Epictetus",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "If you want to improve, you must be content to be thought foolish and stupid. - Epictetus",
    "The greater the difficulty, the more glory in surmounting it. - Epictetus",
    "Only the educated are free. - Epictetus",
    "No great thing is created suddenly. - Epictetus",
    "He with the most who is content with the least. - Epictetus",
    "If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, 'He was ignorant of my other faults, else he would have not mentioned these alone.' - Epictetus",
    "The wise man looks at death with peaceful eyes. - Seneca",
    "While we wait for life, life passes. - Seneca"
]; 