const quotes = [
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
    "Accept the things to which fate binds you, and love the people with whom fate brings you together. - Marcus Aurelius",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "When you arise in the morning, think of what a precious privilege it is to be alive. - Marcus Aurelius",
    "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. - Marcus Aurelius",
    "What stands in the way becomes the way. - Marcus Aurelius",
    "Our life is what our thoughts make it. - Marcus Aurelius",
    "He who fears death will never do anything worthy of a man who is alive. - Seneca",
    "Life is very short and anxious for those who forget the past, neglect the present, and fear the future. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "We suffer more often in imagination than in reality. - Seneca",
    "As long as you live, keep learning how to live. - Seneca",
    "Associate with people who are likely to improve you. - Seneca",
    "If a man knows not to which port he sails, no wind is favorable. - Seneca",
    "The greatest power we have is the power of choice. - Seneca",
    "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
    "If you really want to escape the things that harass you, what you're needing is not to be in a different place but to be a different person. - Seneca",
    "First say to yourself what you would be; then do what you have to do. - Epictetus",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "The key is to keep company only with people who uplift you. - Epictetus",
    "Don't explain your philosophy. Embody it. - Epictetus",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. - Epictetus",
    // ... Add more quotes to reach 100 ...
]; 